server:
  port: 8091

spring:
#  mvc:
#    view:
#      prefix: /
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    encoding: utf-8
    prefix: classpath:/static/
    servlet:
      content-type: text/html
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buy_boot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource

dubbo:
  application:
    name: seller_web