server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buy_boot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1

mybatis:
  type-aliases-package: com.gyw.bean
  mapper-locations: classpath:com/gyw/mapper/*.xml

dubbo:
  registry:
    address: N/A
  application:
    name: order_service
  scan:
    base-packages: com.gyw
  protocol:
    port: 20884
    name: dubbo